import type { AlgorithmCategory, AlgorithmMeta, SafetyLimit, SortAlgorithm } from "./types";

export const categoryOrder: AlgorithmCategory[] = [
  "基础排序",
  "高效排序",
  "非比较排序",
  "冷门排序",
  "整活排序",
  "危险排序",
];

export const safetyLimitsByMode: Record<AlgorithmMeta["runMode"], SafetyLimit> = {
  real: {
    maxSteps: 1_000_000,
    maxRuntimeMs: 8_000,
    maxArraySize: 80,
  },
  limited: {
    maxSteps: 10_000,
    maxRuntimeMs: 3_000,
    maxArraySize: 8,
  },
  simulated: {
    maxSteps: 2_000,
    maxRuntimeMs: 2_500,
    maxArraySize: 24,
  },
  "catalog-only": {
    maxSteps: 0,
    maxRuntimeMs: 0,
    maxArraySize: 0,
  },
};

export const algorithmRegistry: Array<{
  meta: AlgorithmMeta;
  load: () => Promise<SortAlgorithm>;
}> = [
  {
    meta: {
      id: "bubble-sort",
      name: "冒泡排序",
      englishName: "Bubble Sort",
      aliases: ["bubble", "swap sort", "气泡排序"],
      category: "基础排序",
      weirdLevel: 0,
      stable: true,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n^2)", worst: "O(n^2)" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 6, max: 64, default: 28 },
      description: "反复比较相邻元素，把较大的值一路推到右侧。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["bubble-sort"]),
  },
  {
    meta: {
      id: "selection-sort",
      name: "选择排序",
      englishName: "Selection Sort",
      aliases: ["selection", "minimum sort"],
      category: "基础排序",
      weirdLevel: 0,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n^2)", average: "O(n^2)", worst: "O(n^2)" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 6, max: 64, default: 28 },
      description: "每轮选出剩余区间最小值，放到已排序区末尾。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["selection-sort"]),
  },
  {
    meta: {
      id: "insertion-sort",
      name: "插入排序",
      englishName: "Insertion Sort",
      aliases: ["insertion", "card sort"],
      category: "基础排序",
      weirdLevel: 0,
      stable: true,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n^2)", worst: "O(n^2)" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 6, max: 64, default: 28 },
      description: "像整理扑克牌一样，把当前值插入左侧有序区。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["insertion-sort"]),
  },
  {
    meta: {
      id: "merge-sort",
      name: "归并排序",
      englishName: "Merge Sort",
      aliases: ["merge", "divide and conquer"],
      category: "高效排序",
      weirdLevel: 0,
      stable: true,
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 8, max: 80, default: 36 },
      description: "先拆分，再把有序小段逐层合并成完整有序数组。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["merge-sort"]),
  },
  {
    meta: {
      id: "quick-sort",
      name: "快速排序",
      englishName: "Quick Sort",
      aliases: ["quick", "partition sort", "qsort"],
      category: "高效排序",
      weirdLevel: 0,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n^2)" },
      spaceComplexity: "O(log n)",
      recommendedSize: { min: 8, max: 80, default: 36 },
      description: "选择基准值，把小值放左边、大值放右边，再递归处理。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["quick-sort"]),
  },
  {
    meta: {
      id: "heap-sort",
      name: "堆排序",
      englishName: "Heap Sort",
      aliases: ["heap", "binary heap sort"],
      category: "高效排序",
      weirdLevel: 0,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 8, max: 80, default: 36 },
      description: "先建最大堆，再反复把堆顶最大值交换到数组尾部。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["heap-sort"]),
  },
  {
    meta: {
      id: "counting-sort",
      name: "计数排序",
      englishName: "Counting Sort",
      aliases: ["counting", "integer sort"],
      category: "非比较排序",
      weirdLevel: 0,
      stable: true,
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n + k)", average: "O(n + k)", worst: "O(n + k)" },
      spaceComplexity: "O(k)",
      recommendedSize: { min: 8, max: 70, default: 34 },
      description: "统计每个数值出现次数，再按计数回写数组。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["counting-sort"]),
  },
  {
    meta: {
      id: "radix-sort-lsd",
      name: "LSD 基数排序",
      englishName: "LSD Radix Sort",
      aliases: ["radix", "radix sort", "least significant digit"],
      category: "非比较排序",
      weirdLevel: 1,
      stable: true,
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(d(n + k))", average: "O(d(n + k))", worst: "O(d(n + k))" },
      spaceComplexity: "O(n + k)",
      recommendedSize: { min: 8, max: 70, default: 34 },
      description: "从低位到高位按数字位稳定分桶，适合非负整数。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["radix-sort-lsd"]),
  },
  {
    meta: {
      id: "bucket-sort",
      name: "桶排序",
      englishName: "Bucket Sort",
      aliases: ["bucket", "bin sort"],
      category: "非比较排序",
      weirdLevel: 1,
      stable: "depends",
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n + k)", average: "O(n + k)", worst: "O(n^2)" },
      spaceComplexity: "O(n + k)",
      recommendedSize: { min: 8, max: 70, default: 34 },
      description: "把值按范围分进多个桶，桶内排序后再顺序拼接。",
      jokeDescription: "数据分布均匀就顺，不均匀就堵桶。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["bucket-sort"]),
  },
  {
    meta: {
      id: "shell-sort",
      name: "希尔排序",
      englishName: "Shell Sort",
      aliases: ["shellsort", "gap insertion sort"],
      category: "高效排序",
      weirdLevel: 1,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "取决于 gap", average: "取决于 gap", worst: "通常 O(n^2)" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 8, max: 80, default: 36 },
      description: "使用逐渐缩小的 gap 做插入排序，最后退化为普通插入排序收尾。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["shell-sort"]),
  },
  {
    meta: {
      id: "comb-sort",
      name: "梳排序",
      englishName: "Comb Sort",
      aliases: ["comb", "gap bubble sort"],
      category: "冷门排序",
      weirdLevel: 1,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n log n)", average: "O(n^2)", worst: "O(n^2)" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 8, max: 70, default: 34 },
      description: "冒泡排序的 gap 改良版，先远距离交换，再收敛到相邻比较。",
      jokeDescription: "梳掉乌龟，留点兔子。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["comb-sort"]),
  },
  {
    meta: {
      id: "cocktail-shaker-sort",
      name: "鸡尾酒排序",
      englishName: "Cocktail Shaker Sort",
      aliases: ["cocktail sort", "bidirectional bubble sort"],
      category: "基础排序",
      weirdLevel: 1,
      stable: true,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n^2)", worst: "O(n^2)" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 6, max: 64, default: 28 },
      description: "冒泡排序的双向版本，先向右冒泡，再向左冒泡。",
      jokeDescription: "冒泡喝多了开始往返跑。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["cocktail-shaker-sort"]),
  },
  {
    meta: {
      id: "odd-even-sort",
      name: "奇偶排序",
      englishName: "Odd-Even Sort",
      aliases: ["brick sort", "odd even sort"],
      category: "基础排序",
      weirdLevel: 1,
      stable: true,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n^2)", worst: "O(n^2)" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 6, max: 64, default: 28 },
      description: "轮流比较奇数位置相邻对和偶数位置相邻对，直到没有交换。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["odd-even-sort"]),
  },
  {
    meta: {
      id: "gnome-sort",
      name: "地精排序",
      englishName: "Gnome Sort",
      aliases: ["gnome", "stupid sort"],
      category: "冷门排序",
      weirdLevel: 1,
      stable: true,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n^2)", worst: "O(n^2)" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 6, max: 64, default: 28 },
      description: "发现逆序就交换并退一步，直到一路走到末尾。",
      jokeDescription: "像插入排序边走边后悔。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["gnome-sort"]),
  },
  {
    meta: {
      id: "pancake-sort",
      name: "煎饼排序",
      englishName: "Pancake Sort",
      aliases: ["pancake", "prefix reversal sort"],
      category: "冷门排序",
      weirdLevel: 2,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n^2)", worst: "O(n^2)" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 4, max: 50, default: 24 },
      description: "只允许翻转前缀，把当前最大值翻到未排序区末尾。",
      jokeDescription: "动画效果比效率更香。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["pancake-sort"]),
  },
  {
    meta: {
      id: "cycle-sort",
      name: "循环排序",
      englishName: "Cycle Sort",
      aliases: ["cycle", "minimum write sort"],
      category: "冷门排序",
      weirdLevel: 1,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n^2)", average: "O(n^2)", worst: "O(n^2)" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 6, max: 48, default: 24 },
      description: "把每个元素直接轮换到最终位置，尽量减少写入次数。",
      jokeDescription: "写得少，想得多。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["cycle-sort"]),
  },
  {
    meta: {
      id: "patience-sort",
      name: "耐心排序",
      englishName: "Patience Sorting",
      aliases: ["patience", "card pile sort"],
      category: "冷门排序",
      weirdLevel: 1,
      stable: false,
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n log n)", worst: "O(n log n)" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 6, max: 64, default: 28 },
      description: "像发扑克牌一样分堆，再反复取各堆顶部最小值合并。",
      jokeDescription: "排序像打牌，输了也优雅。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["patience-sort"]),
  },
  {
    meta: {
      id: "binary-insertion-sort",
      name: "二分插入排序",
      englishName: "Binary Insertion Sort",
      aliases: ["binary insertion", "binary insert sort"],
      category: "基础排序",
      weirdLevel: 0,
      stable: true,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n log n)", average: "O(n^2)", worst: "O(n^2)" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 6, max: 64, default: 28 },
      description: "用二分查找确定插入位置，再移动元素完成插入。",
      jokeDescription: "脑子快了，手还是要搬砖。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["binary-insertion-sort"]),
  },
  {
    meta: {
      id: "bottom-up-merge-sort",
      name: "自底向上归并排序",
      englishName: "Bottom-up Merge Sort",
      aliases: ["iterative merge sort"],
      category: "高效排序",
      weirdLevel: 0,
      stable: true,
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 8, max: 80, default: 32 },
      description: "从长度 1 的小块开始两两合并，避免递归拆分。",
      jokeDescription: "不递归，也能把队伍排得明明白白。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["bottom-up-merge-sort"]),
  },
  {
    meta: {
      id: "natural-merge-sort",
      name: "自然归并排序",
      englishName: "Natural Merge Sort",
      aliases: ["natural mergesort"],
      category: "高效排序",
      weirdLevel: 0,
      stable: true,
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n log n)", worst: "O(n log n)" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 8, max: 80, default: 32 },
      description: "先识别数组里已经连续递增的片段，再逐步合并。",
      jokeDescription: "尊重原数组的努力，能少干就少干。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["natural-merge-sort"]),
  },
  {
    meta: {
      id: "three-way-quick-sort",
      name: "三路快速排序",
      englishName: "3-way Quick Sort",
      aliases: ["three-way partition quicksort", "Dutch quicksort"],
      category: "高效排序",
      weirdLevel: 0,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n^2)" },
      spaceComplexity: "O(log n)",
      recommendedSize: { min: 8, max: 80, default: 32 },
      description: "把区间分成小于、等于、大于 pivot 三段，重复值很多时更稳。",
      jokeDescription: "看到重复值不纠结，直接给它们单独开一队。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["three-way-quick-sort"]),
  },
  {
    meta: {
      id: "dual-pivot-quick-sort",
      name: "双轴快速排序",
      englishName: "Dual-pivot Quick Sort",
      aliases: ["dual pivot quicksort", "Yaroslavskiy quicksort"],
      category: "高效排序",
      weirdLevel: 1,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n^2)" },
      spaceComplexity: "O(log n)",
      recommendedSize: { min: 8, max: 80, default: 32 },
      description: "一次选两个 pivot，把数据切成三段分别递归。",
      jokeDescription: "一个裁判不够，那就请两个。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["dual-pivot-quick-sort"]),
  },
  {
    meta: {
      id: "intro-sort",
      name: "内省排序",
      englishName: "Introsort",
      aliases: ["introspective sort"],
      category: "高效排序",
      weirdLevel: 1,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" },
      spaceComplexity: "O(log n)",
      recommendedSize: { min: 8, max: 80, default: 32 },
      description: "以快速排序开局，递归深度异常时切换堆排序兜底。",
      jokeDescription: "快排开始自我反省时，事情通常就稳了。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["intro-sort"]),
  },
  {
    meta: {
      id: "tim-sort",
      name: "Tim 排序",
      englishName: "TimSort",
      aliases: ["timsort", "Python list sort"],
      category: "高效排序",
      weirdLevel: 1,
      stable: true,
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n log n)", worst: "O(n log n)" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 8, max: 80, default: 32 },
      description: "结合插入排序和归并排序，利用现实数据中已有的有序 run。",
      jokeDescription: "工业级老油条，最会捡现成便宜。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["tim-sort"]),
  },
  {
    meta: {
      id: "radix-sort-msd",
      name: "最高位基数排序",
      englishName: "MSD Radix Sort",
      aliases: ["most significant digit radix sort"],
      category: "非比较排序",
      weirdLevel: 1,
      stable: "depends",
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(d(n + k))", average: "O(d(n + k))", worst: "O(d(n + k))" },
      spaceComplexity: "O(n + k)",
      recommendedSize: { min: 8, max: 80, default: 32 },
      description: "从最高有效位开始分桶，再递归处理每个桶。",
      jokeDescription: "先看大方向，再处理小数位。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["radix-sort-msd"]),
  },
  {
    meta: {
      id: "pigeonhole-sort",
      name: "鸽巢排序",
      englishName: "Pigeonhole Sort",
      aliases: ["pigeon-hole sort"],
      category: "非比较排序",
      weirdLevel: 1,
      stable: "depends",
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n + range)", average: "O(n + range)", worst: "O(n + range)" },
      spaceComplexity: "O(range)",
      recommendedSize: { min: 6, max: 64, default: 28 },
      description: "为最小值到最大值之间的每个值准备槽位，计数后按槽位写回。",
      jokeDescription: "值域小就是豪宅，一人一个坑位。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["pigeonhole-sort"]),
  },
  {
    meta: {
      id: "american-flag-sort",
      name: "美式旗帜排序",
      englishName: "American Flag Sort",
      aliases: ["american flag", "in-place radix sort"],
      category: "非比较排序",
      weirdLevel: 2,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "limited",
      source: "built-in",
      timeComplexity: { best: "O(d(n + k))", average: "O(d(n + k))", worst: "O(d(n + k))" },
      spaceComplexity: "O(k)",
      recommendedSize: { min: 8, max: 48, default: 24 },
      description: "原地 MSD 基数排序，真实循环置换实现复杂；首版限制规模并模拟桶边界写回。",
      jokeDescription: "看起来像分桶，实际像在桶之间搬家。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["american-flag-sort"]),
  },
  {
    meta: {
      id: "tree-sort",
      name: "树排序",
      englishName: "Tree Sort",
      aliases: ["binary tree sort", "BST sort"],
      category: "冷门排序",
      weirdLevel: 1,
      stable: false,
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n^2)" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 6, max: 64, default: 28 },
      description: "把元素插入二叉搜索树，再中序遍历得到有序序列。",
      jokeDescription: "先种树，再摘果。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["tree-sort"]),
  },
  {
    meta: {
      id: "tournament-sort",
      name: "锦标赛排序",
      englishName: "Tournament Sort",
      aliases: ["selection tree sort"],
      category: "冷门排序",
      weirdLevel: 1,
      stable: false,
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 6, max: 64, default: 28 },
      description: "每轮像淘汰赛一样找出当前最小值并输出。",
      jokeDescription: "所有数字打一场比赛，冠军先出列。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["tournament-sort"]),
  },
  {
    meta: {
      id: "strand-sort",
      name: "链条排序",
      englishName: "Strand Sort",
      aliases: ["strand"],
      category: "冷门排序",
      weirdLevel: 2,
      stable: true,
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n^2)", worst: "O(n^2)" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 6, max: 48, default: 24 },
      description: "不断从剩余序列抽出递增子序列，再归并到输出序列。",
      jokeDescription: "一缕一缕拆，最后织回去。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["strand-sort"]),
  },
  {
    meta: {
      id: "library-sort",
      name: "图书馆排序",
      englishName: "Library Sort",
      aliases: ["gapped insertion sort"],
      category: "冷门排序",
      weirdLevel: 2,
      stable: "depends",
      inPlace: false,
      canRunForever: false,
      runMode: "limited",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n log n)", worst: "O(n^2)" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 6, max: 48, default: 24 },
      description: "在数组里预留空位降低搬移成本；首版用受限插入演示空位思想。",
      jokeDescription: "书架留空格，管理员少挪书。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["library-sort"]),
  },
  {
    meta: {
      id: "bead-sort",
      name: "珠排序",
      englishName: "Bead Sort",
      aliases: ["gravity sort"],
      category: "冷门排序",
      weirdLevel: 3,
      stable: "not-applicable",
      inPlace: false,
      canRunForever: false,
      runMode: "simulated",
      source: "built-in",
      timeComplexity: { best: "O(n + max)", average: "O(n * max)", worst: "O(n * max)" },
      spaceComplexity: "O(n * max)",
      recommendedSize: { min: 5, max: 24, default: 12 },
      description: "用珠子和重力隐喻排序，只适合非负整数；真实矩阵可能很大，所以首版模拟。",
      jokeDescription: "让重力打工，但别真把内存铺成珠帘。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["bead-sort"]),
  },
  {
    meta: {
      id: "spaghetti-sort",
      name: "意大利面排序",
      englishName: "Spaghetti Sort",
      aliases: ["poll sort", "linear-time physical sort"],
      category: "冷门排序",
      weirdLevel: 4,
      stable: "not-applicable",
      inPlace: false,
      canRunForever: false,
      runMode: "simulated",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n)", worst: "O(n)" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 5, max: 24, default: 12 },
      description: "把数值想象成面条长度，反复抽出最长面条；网页中只模拟物理过程。",
      jokeDescription: "理论上线性，现实中先去厨房。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["spaghetti-sort"]),
  },
  {
    meta: {
      id: "stooge-sort",
      name: "三傻排序",
      englishName: "Stooge Sort",
      aliases: ["stooge"],
      category: "危险排序",
      weirdLevel: 4,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "limited",
      source: "built-in",
      timeComplexity: { best: "O(n^2.7095)", average: "O(n^2.7095)", worst: "O(n^2.7095)" },
      spaceComplexity: "O(log n)",
      recommendedSize: { min: 3, max: 8, default: 6 },
      description: "递归排序前 2/3、后 2/3、再前 2/3，复杂度极高，必须限制数组规模。",
      jokeDescription: "不是三个人快，是三个人一起慢。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["stooge-sort"]),
  },
  {
    meta: {
      id: "slow-sort",
      name: "慢排序",
      englishName: "Slow Sort",
      aliases: ["slowsort", "multiply and surrender"],
      category: "危险排序",
      weirdLevel: 4,
      stable: false,
      inPlace: true,
      canRunForever: false,
      runMode: "simulated",
      source: "built-in",
      timeComplexity: { best: "super-polynomial", average: "super-polynomial", worst: "super-polynomial" },
      spaceComplexity: "O(log n)",
      recommendedSize: { min: 3, max: 8, default: 6 },
      description: "故意低效的递归排序，增长过快；仅在极小规模模拟，避免拖垮页面。",
      jokeDescription: "它不是慢，它是把慢当成设计目标。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["slow-sort"]),
  },
  {
    meta: {
      id: "bozo-sort",
      name: "笨蛋排序",
      englishName: "Bozo Sort",
      aliases: ["bozosort", "random swap sort"],
      category: "整活排序",
      weirdLevel: 4,
      stable: "not-applicable",
      inPlace: true,
      canRunForever: true,
      runMode: "limited",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "unbounded", worst: "∞" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 4, max: 7, default: 5 },
      description: "随机交换两个位置直到有序，可能长期不收敛，所以限制规模和尝试次数。",
      jokeDescription: "比猴子排序稍微克制，但也只是稍微。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["bozo-sort"]),
  },
  {
    meta: {
      id: "miracle-sort",
      name: "奇迹排序",
      englishName: "Miracle Sort",
      aliases: ["miraclesort", "wait sort"],
      category: "整活排序",
      weirdLevel: 4,
      stable: "not-applicable",
      inPlace: true,
      canRunForever: true,
      runMode: "simulated",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "unbounded", worst: "∞" },
      spaceComplexity: "O(1)",
      recommendedSize: { min: 4, max: 12, default: 6 },
      description: "什么也不做，等待数组自己变有序；真实运行没有意义，只做图鉴式模拟。",
      jokeDescription: "把希望交给宇宙，把浏览器留给用户。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["miracle-sort"]),
  },
  {
    meta: {
      id: "bogo-sort",
      name: "猴子排序",
      englishName: "Bogo Sort",
      aliases: ["bogo", "stupid sort", "random sort", "随机乱排"],
      category: "整活排序",
      weirdLevel: 4,
      stable: "not-applicable",
      inPlace: false,
      canRunForever: true,
      runMode: "limited",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n * n!)", worst: "∞" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 4, max: 7, default: 5 },
      description: "随机打乱，检查是否有序；不行就继续赌。",
      jokeDescription: "这是算法界的掷骰子，不限制会把浏览器拖进泥潭。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["bogo-sort"]),
  },
  {
    meta: {
      id: "stalin-sort",
      name: "斯大林排序",
      englishName: "Stalin Sort",
      aliases: ["stalin", "delete sort", "purge sort"],
      category: "整活排序",
      weirdLevel: 3,
      stable: true,
      inPlace: false,
      canRunForever: false,
      runMode: "real",
      source: "built-in",
      timeComplexity: { best: "O(n)", average: "O(n)", worst: "O(n)" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 6, max: 32, default: 18 },
      description: "扫描数组，遇到破坏递增秩序的元素就直接删除。",
      jokeDescription: "不是排序，是把不配合的元素移出队伍。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["stalin-sort"]),
  },
  {
    meta: {
      id: "sleep-sort",
      name: "睡眠排序",
      englishName: "Sleep Sort",
      aliases: ["sleep", "timer sort", "延时排序"],
      category: "危险排序",
      weirdLevel: 4,
      stable: "depends",
      inPlace: false,
      canRunForever: false,
      runMode: "simulated",
      source: "built-in",
      timeComplexity: { best: "O(max value)", average: "O(max value)", worst: "O(max value)" },
      spaceComplexity: "O(n)",
      recommendedSize: { min: 5, max: 18, default: 10 },
      description: "真实版本按数值设置定时器，谁先醒谁先输出；首版只模拟，不真实开大量定时器。",
      jokeDescription: "让数字睡觉不是问题，让浏览器陪睡才是问题。",
    },
    load: () => import("./algorithms").then((module) => module.algorithms["sleep-sort"]),
  },
];

export function findRegistryEntry(id: string) {
  return algorithmRegistry.find((entry) => entry.meta.id === id) ?? algorithmRegistry[0];
}

export function getSafetyLimit(meta: AlgorithmMeta): SafetyLimit {
  const base = safetyLimitsByMode[meta.runMode];

  return {
    maxSteps: base.maxSteps,
    maxRuntimeMs: base.maxRuntimeMs,
    maxArraySize: Math.min(base.maxArraySize, meta.recommendedSize.max),
  };
}

export function searchAlgorithms(query: string) {
  const needle = query.trim().toLowerCase();

  if (!needle) {
    return algorithmRegistry;
  }

  return algorithmRegistry.filter(({ meta }) => {
    const haystack = [
      meta.name,
      meta.englishName,
      meta.category,
      meta.description,
      meta.jokeDescription ?? "",
      ...meta.aliases,
    ]
      .join(" ")
      .toLowerCase();

    return haystack.includes(needle);
  });
}
